version: '3.1'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx.certs:/etc/nginx/certs:ro
      - nginx.vhost.d:/etc/nginx/vhost.d
      - nginx.html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - "nginx-proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx.certs:/etc/nginx/certs:rw
      - nginx.vhost.d:/etc/nginx/vhost.d
      - nginx.html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
  ghost:
    image: ghost:2-alpine
    restart: always
    depends_on:
      - "nginx-proxy"
    expose:
      - "2368"
    volumes:
      - ghost.data:/var/lib/ghost/content
    environment:
      - url=https://www.example-domain.com
      - NODE_ENV=production
      - VIRTUAL_HOST=www.example-domain.com,example-domain.com
      - LETSENCRYPT_HOST=www.example-domain.com,example-domain.com
      - LETSENCRYPT_EMAIL=info@example-domain.com
volumes:
  nginx.vhost.d:
  nginx.html:
  nginx.certs:
  ghost.data:
